version: '3'
services:

  # MySQL service
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    networks:
      - myappNetwork
    volumes:
      - mysql-data:/var/lib/mysql

  # Spring Boot services
  springboot-app:
    image: karouihelmi/devops:latest
    ports:
      - "8085:8085"
    depends_on:
      - mysql
    networks:
      - myappNetwork


networks:
  myappNetwork:


volumes:
  mysql-data: