version: '3'
services:

  # MySQL service
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    networks:
      - myappNetwork
    volumes:
      - mysql-data:/var/lib/mysql

  # Spring Boot service
  springboot-app:
    image: achrefbouthouri/devops:latest
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    networks:
      - myappNetwork

  # Angular app service
  angular-app:
    image: achrefbouthouri/devops-front:latest
    ports:
      - "80:80"
    depends_on:
      - springboot-app
    networks:
      - myappNetwork

networks:
  myappNetwork:


volumes:
  mysql-data:
